### PR TITLE
Travis auto-deploy

### PR DESCRIPTION
**Pull request by hexylena**
@bgruening, could I trouble you to fill out your (encrypted) pypi credentials? :) @shiltemann is waiting on an updated pypi release I believe from #1

### CODE REVIEW

**Comment by hexylena** [comment]
ping @bgruening (I know you're busy, but if you have a minute, this would be very helpful)

**Comment by bgruening** [comment]
Oh, this was a PR ... ähm ähm

**Comment by bgruening** [comment]
I will get my secure tm and will merge it, sorry.

**Comment by hexylena** [comment]
No problem, thank you so much!

**Comment by bgruening** [comment]
It's failing, tm more.

**Pull request merged**
